### ISSUE TITLE
HTML getting rendered in the response field

### ISSUE THREAD

**Issue by boyney123** [boyney123/mockit#21]
## What you did:

Add this HTML snippet inside the response field. And you will see it render...

```
<div style='width: 500px; background-color: red;'>Hey you!</div>
```

## What happened:

It rendered the HTML

![image](https://user-images.githubusercontent.com/3268013/56524971-3ef4fa80-6542-11e9-93c2-e50c947e6b35.png)

## Suggested solution:

I think at the moment mockit will only return JSON responses. It would be nice that HTML does not get rendered as HTML, but also maybe give the user an error if HTML was added?

Option 2: We can try and support HTML as responses but not sure what would be involved.

**Comment by samrith-s** [comment]
Hey @boyney123,

Good work with Mockit! I'm keen on contributing regularly and immensely to it and also use it in my workplace.

I can take this up. Seems like a good way to delve into Mockit code and get my hands dirty!

**Comment by boyney123** [comment]
Hey @samrith-s, 

Yeah, that sounds great! 🙇 👍 

Yeah give it a go and see what you can find. Mockit is using `react-json-editor-ajrm` for that JSON editor thing, so that might be rendering the HTML, not to sure though.

**Comment by samrith-s** [comment]
@boyney123 I had a look at it.

The issue seems to be the package `react-json-editor-ajrm`. It does not allow setting HTML values. It throws multiple errors in the console and doesn't save the value either. 

I think it'd be ideal to go for something better. Something a la Postman. Probably something like this: http://securingsincity.github.io/react-ace/

**Comment by boyney123** [comment]
@samrith-s yeah sure give it ago see what you can do 👍 

I think at some point we should validate the inputs in this form. I'm adding some new inputs as part of #4 , so validation will need to come at some point. Looking at Formik at the moment.

But yeah see what you can do, and get that JSON edited and saved with `react-ace`

**Comment by samrith-s** [comment]
Agreed. But I think we should ask the user to set a response type mandatorily, and strip the validation from the editor. Another function which validates, based on response content type, before saving it to state. 

Right now, it’s too coupled with the editor and dependent on the editor itself, which shouldn’t ideally be the case.

**Comment by samrith-s** [comment]
Quick question, @boyney123 

I have integrated Ace Editor, but I wanna save the parser as well. Which validates data. How do I save it to the `editRoutes`?

I wanna add something like `editRoutes.parserType` which will be one of `html/plain-text' or `json`.

**Comment by samrith-s** [comment]
@boyney123 Could you maybe help me out here? My React App isn't hot reloading. Keep getting an error, after running `docker-compose up -d`.

**Comment by wohlben** [comment]
Hey @samrith-s 

@boyney123  left out the --build flag i mentioned in my PR some time ago - that forces docker compose to rebuild the images and consequently updates the code :)

but hot reloading is only possible by mounting the code from your workstation into the container

looking at the Dockerfile, you should be able to just mount the whole directory into each WORKDIR, so something like this could work... but is untested

```
version: "3"
services:
  mockit-routes:
    image: "mockit-routes"
    build: "mockit-routes"
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/mockit-routes
  mockit-server:
    image: "mockit-server"
    build: "server"
    ports:
      - 4000:4000
    volumes:
      - .:/usr/src/mockit-server
  mockit-client:
    image: "mockit-client"
    build: "client"
    ports:
      - 5000:3000
    environment:
      - REACT_APP_MOCKIT_SERVER_URL=http://localhost:3000
      - REACT_APP_MOCKIT_API_URL=http://localhost:4000
    volumes:
      - .:/usr/src/mockit-client
```
by mounting the whole directory instead of just the routes.json, the used routes json changes from src/config/routes.json to ./configuration/routes.json

ps: feel free to ping me if you have any questions about docker/docker-compose @boyney123, i do have some experience on the topic :)
